import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class AppLocalizations extends ChangeNotifier {
  AppLocalizations() : _locale = const Locale('en');

  Locale _locale;

  Locale get locale => _locale;

  static const supportedLocales = [Locale('en'), Locale('es')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'app_title': 'Agri-Guard AI',
      'splash_subtitle': 'Smart Agricultural Intelligence Platform',
      'login_title': 'Login / Registration',
      'login_subtitle': 'For farmers, buyers & agricultural stakeholders',
      'login_email_phone': 'Email / Phone',
      'login_password': 'Password',
      'login_continue': 'Continue',
      'login_forgot_password': 'Forgot password?',
      'select_user_type_title': 'Select User Type',
      'select_user_type_subtitle': 'Choose how you will use Agri-Guard AI',
      'select_user_type_continue_as': 'Continue as',
      'role_farmer_title': 'Farmer',
      'role_farmer_subtitle': 'Register farms, record activities, receive weather & crop health support',
      'role_buyer_title': 'Buyer / Aggregator',
      'role_buyer_subtitle': 'Search crops, view predictions, find produce locations & plan sourcing',
      'home_welcome_farmer': 'Welcome Farmer',
      'home_welcome_buyer': 'Welcome Buyer',
      'home_search_hint': 'Search crops, regions, farmers, or harvests',
      'home_feature_farm_registration': 'Register Farm',
      'home_feature_farm_registration_desc': 'Add farm details & GPS location',
      'home_feature_farm_activities': 'Farm Activities',
      'home_feature_farm_activities_desc': 'Log planting, stages & fertilizer',
      'home_feature_weather': 'Weather Advisory',
      'home_feature_weather_desc': 'Temperature, humidity, rainfall & wind',
      'home_feature_disease': 'Crop Health Advisory',
      'home_feature_disease_desc': 'Disease detection & recommendations',
      'home_feature_produce_availability': 'Crop Availability',
      'home_feature_produce_availability_desc': 'Regional supply & harvest windows',
      'home_feature_produce_prediction': 'Produce Prediction',
      'home_feature_produce_prediction_desc': 'Quantity, date & confidence forecasts',
      'home_feature_produce_map': 'Produce Map',
      'home_feature_produce_map_desc': 'Farmers, locations & expected quantity',
      'home_feature_regional_forecast': 'Regional Forecast',
      'home_feature_regional_forecast_desc': 'Production trends by region',
      'home_section_features': 'Features',
      'home_section_data_generated': 'Data Generated',
      'home_data_farmers': 'Active Farmers',
      'home_data_farms': 'Registered Farms',
      'home_data_crops': 'Available Crops',
      'home_data_predictions': 'Predicted Tons',
      'home_data_flow': 'All data is stored in the Agri-Guard database and feeds the Produce Prediction System.',
      'app_navigation_home': 'Home',
      'app_navigation_search': 'Search',
      'app_navigation_predictions': 'Predictions',
      'app_navigation_advisory': 'Advisory',
      'app_navigation_profile': 'Profile',
      'prediction_dashboard_title': 'Prediction Dashboard',
      'prediction_dashboard_subtitle': 'Primary crop forecast',
      'prediction_card_predicted_quantity': 'Predicted Quantity',
      'prediction_card_expected_harvest': 'Expected Harvest',
      'prediction_card_confidence_level': 'Confidence Level',
      'prediction_breakdown_weather': 'Weather data',
      'prediction_breakdown_farm': 'Farm activity logs',
      'prediction_breakdown_historical': 'Historical yield',
      'availability_title': 'Produce Availability',
      'availability_subtitle': 'Predicted crop availability across regions',
      'profile_title': 'Profile',
      'profile_switch_role': 'Switch Role',
      'profile_switch_role_subtitle': 'Change between Farmer and Buyer',
      'profile_about_title': 'About Agri-Guard AI',
      'profile_about_subtitle': 'Farmers generate data → Predictions power buyer decisions',
      'profile_logout': 'Logout',
      'weather_title': 'Weather Advisory',
      'weather_try_again': 'Try Again',
      'weather_current_conditions': 'Current Conditions',
      'weather_farming_advisory': 'Farming Advisory',
      'weather_need_api_key': 'Weather API key is required to fetch weather data.',
      'weather_change_key': 'Change API key',
      'weather_refresh': 'Refresh location & weather',
      'weather_detecting': 'Detecting location & fetching weather...',
      'weather_missing_api_key': 'Please add your weather API key to continue.',
      'disease_title': 'Crop Health Advisory',
      'disease_button': 'Get Disease Advisory',
      'disease_help': 'Enter crop and region above to fetch live disease advisory.',
      'disease_crop': 'Crop',
      'disease_region': 'Region',
      'disease_symptoms': 'Observed symptoms',
      'disease_quality_score': 'Quality score (1-10)',
      'disease_advisory': 'Advisory',
      'disease_risk': 'Risk',
      'disease_confidence': 'Confidence',
      'disease_evidence': 'Evidence',
      'farm_advisory_title': 'Farm Advisory System',
      'farm_advisory_purpose': 'Help farmers manage farms, collect real-time agricultural data, and generate datasets for retraining the prediction model.',
      'farm_advisory_card_disease': 'Crop Health Advisory',
      'farm_advisory_card_disease_desc': 'Disease, confidence & recommendations',
      'role_selection_continue_as': 'Continue as',
      'farmer_registration_title': 'Farmer Registration',
      'farm_registration_title': 'Farm Registration',
      'farm_registration_subtitle': 'Each farm has its own coordinates — a farmer may own multiple farms in different locations.',
      'farm_registration_name': 'Farm Name',
      'farm_registration_size': 'Farm Size (acres)',
      'farm_registration_crop': 'Crop Type',
      'farm_registration_button': 'Register Farm',
      'farm_activity_title': 'Farm Activity Tracking',
      'farm_activity_save': 'Save Activity',
      'farm_activity_success': 'Activity recorded successfully!',
      'farm_activity_dates': 'Please select both dates',
      'farm_activity_planting_date': 'Planting Date',
      'farm_activity_crop_stage': 'Crop Stage',
      'farm_activity_fertilizer_applied': 'Fertilizer Applied',
      'farm_activity_fertilizer_hint': 'e.g. NPK 15-15-15',
      'farm_activity_enter_fertilizer': 'Enter fertilizer applied',
      'farm_activity_expected_harvest_date': 'Expected Harvest Date',
      'farm_advisory_buyer_search': 'Search Produce Instead',
      'map_title': 'Produce Map',
      'search_title': 'Search Produce',
      'search_filter_region': 'Filter by Region',
      'search_no_results': 'No results found for your query.',
      'search_hint': 'Search crops, regions, farmers, or harvests',
      'weather_search_query': 'Search crops, regions, farmers, or harvests',
      'nav_search_label': 'Search produce',
      'no_produce_results': 'No produce found. Try another search.',
      'by_location': 'By location',
      'individual_records': 'Individual records',
      'weather_refresh_location': 'Refresh location & weather',
      'weather_key_required': 'Please add your weather API key to continue.',
      'language': 'Language',
      'language_english': 'English',
      'language_spanish': 'Spanish',
      'location_gps_error': 'Could not read GPS coordinates.',
      'failed_disease_advisory': 'Failed to load disease advisory: {error}',
      'enter_crop_region': 'Please enter both crop and region.',
      'disease_unknown': 'Unknown',
      'no_data_summary': 'No advisory data yet. Enter crop and region to begin.',
      'farmer_registration_instructions': 'Location powers weather advisory, crop health alerts, and buyer search by region.',
      'farmer_registration_full_name': 'Full Name',
      'farmer_registration_name_error': 'Enter your name',
      'farmer_registration_phone': 'Phone Number',
      'farmer_registration_phone_error': 'Enter phone number',
      'farmer_registration_location_title': 'Farmer Location',
      'farmer_registration_complete_form': 'Please complete the form',
      'farmer_registration_success_prefix': 'Farmer registered in',
      'map_coming_soon': 'Google Maps — coming soon',
      'map_active_producers': 'Active Producers',
      'prediction_region_x': 'Region: {region}',
      'prediction_card_predicted_quantity_desc': 'Based on farm size & activity logs',
      'prediction_card_expected_harvest_desc': 'Optimal harvest window',
      'prediction_card_confidence_level_desc': 'Model accuracy for this region',
      'prediction_confidence_breakdown': 'Confidence Breakdown',
      'prediction_other_forecasts': 'Other Crop Forecasts',
      'home_section_recent_predictions': 'Recent Predictions',
      'prediction_expected_label': 'Expected:',
      'search_by_location': 'By location',
      'search_individual_records': 'Individual records',
      'search_predicted_quantity': 'Predicted quantity: {quantity}',
      'search_farmers': 'Farmers: {count}',
      'search_farmer_label': 'Farmer: {name}',
      'search_qty_label': 'Qty: {quantity}',
      'search_harvest_label': 'Harvest: {harvest}',
      'availability_overview_title': 'Regional Overview',
      'availability_quantity': 'Quantity:',
      'availability_expected_harvest': 'Expected Harvest:',
      'availability_confidence': 'Confidence:',
      'prediction_hub_title': 'Produce Prediction System',
      'prediction_hub_purpose': 'Combines historical agricultural data with real-time farmer data to predict crop availability, harvest quantity, and regional produce distribution.',
      'prediction_hub_features_title': 'Features',
      'prediction_hub_model_inputs_title': 'Model Inputs',
      'prediction_hub_input_historical': 'Historical Data',
      'prediction_hub_input_farmer': 'Farmer Data',
      'prediction_hub_input_weather': 'Weather Data',
      'prediction_hub_output_description': 'Output: Trained model that predicts harvest quantity, availability dates, and regional distribution.',
      'regional_forecast_title': 'Regional Forecast',
      'regional_forecast_description': 'Production trends by region (mock data)',
      'home_section_data': 'Data Generated',
    },
    'es': {
      'app_title': 'Agri-Guard IA',
      'splash_subtitle': 'Plataforma inteligente de agricultura',
      'login_title': 'Inicio de sesión / Registro',
      'login_subtitle': 'Para agricultores, compradores y partes interesadas agrícolas',
      'login_email_phone': 'Correo / Teléfono',
      'login_password': 'Contraseña',
      'login_continue': 'Continuar',
      'login_forgot_password': '¿Olvidaste tu contraseña?',
      'select_user_type_title': 'Seleccionar tipo de usuario',
      'select_user_type_subtitle': 'Elige cómo usarás Agri-Guard IA',
      'select_user_type_continue_as': 'Continuar como',
      'role_farmer_title': 'Agricultor',
      'role_farmer_subtitle': 'Registra granjas, registra actividades, recibe clima y soporte de salud de cultivos',
      'role_buyer_title': 'Comprador / Agregador',
      'role_buyer_subtitle': 'Busca cultivos, ve predicciones, encuentra ubicaciones de productos y planifica suministros',
      'home_welcome_farmer': 'Bienvenido Agricultor',
      'home_welcome_buyer': 'Bienvenido Comprador',
      'home_search_hint': 'Buscar cultivos, regiones, agricultores o cosechas',
      'home_feature_farm_registration': 'Registrar Granja',
      'home_feature_farm_registration_desc': 'Agrega detalles de la granja y ubicación GPS',
      'home_feature_farm_activities': 'Actividades de Granja',
      'home_feature_farm_activities_desc': 'Registra siembra, etapas y fertilizante',
      'home_feature_weather': 'Asesoría Climática',
      'home_feature_weather_desc': 'Temperatura, humedad, lluvia y viento',
      'home_feature_disease': 'Asesoría de Salud de Cultivos',
      'home_feature_disease_desc': 'Detección de enfermedades y recomendaciones',
      'home_feature_produce_availability': 'Disponibilidad de Productos',
      'home_feature_produce_availability_desc': 'Suministro regional y ventanas de cosecha',
      'home_feature_produce_prediction': 'Predicción de Productos',
      'home_feature_produce_prediction_desc': 'Cantidad, fecha y confianza',
      'home_feature_produce_map': 'Mapa de Productos',
      'home_feature_produce_map_desc': 'Agricultores, ubicaciones y cantidad esperada',
      'home_feature_regional_forecast': 'Pronóstico Regional',
      'home_feature_regional_forecast_desc': 'Tendencias de producción por región',
      'home_section_features': 'Características',
      'home_section_data_generated': 'Datos Generados',
      'home_data_farmers': 'Agricultores activos',
      'home_data_farms': 'Granjas registradas',
      'home_data_crops': 'Cultivos disponibles',
      'home_data_predictions': 'Toneladas predichas',
      'home_data_flow': 'Todos los datos se almacenan en la base de datos Agri-Guard y alimentan el Sistema de Predicción de Producción.',
      'app_navigation_home': 'Inicio',
      'app_navigation_search': 'Buscar',
      'app_navigation_predictions': 'Predicciones',
      'app_navigation_advisory': 'Asesoría',
      'app_navigation_profile': 'Perfil',
      'prediction_dashboard_title': 'Panel de Predicción',
      'prediction_dashboard_subtitle': 'Pronóstico de cultivos principal',
      'prediction_card_predicted_quantity': 'Cantidad Predicha',
      'prediction_card_expected_harvest': 'Cosecha Esperada',
      'prediction_card_confidence_level': 'Nivel de Confianza',
      'prediction_breakdown_weather': 'Datos meteorológicos',
      'prediction_breakdown_farm': 'Registros de actividades de granja',
      'prediction_breakdown_historical': 'Rendimiento histórico',
      'availability_title': 'Disponibilidad de Productos',
      'availability_subtitle': 'Disponibilidad de cultivos prevista en regiones',
      'profile_title': 'Perfil',
      'profile_switch_role': 'Cambiar Rol',
      'profile_switch_role_subtitle': 'Cambiar entre Agricultor y Comprador',
      'profile_about_title': 'Acerca de Agri-Guard IA',
      'profile_about_subtitle': 'Los agricultores generan datos → Las predicciones impulsan decisiones de compra',
      'profile_logout': 'Cerrar sesión',
      'weather_title': 'Asesoría Climática',
      'weather_try_again': 'Intentar de nuevo',
      'weather_current_conditions': 'Condiciones Actuales',
      'weather_farming_advisory': 'Asesoría Agrícola',
      'weather_need_api_key': 'Se requiere una clave de API de clima para obtener datos meteorológicos.',
      'weather_change_key': 'Cambiar clave de API',
      'weather_refresh': 'Actualizar ubicación y clima',
      'weather_detecting': 'Detectando ubicación y obteniendo clima...',
      'weather_missing_api_key': 'Por favor agrega tu clave de API de clima para continuar.',
      'disease_title': 'Asesoría de Salud de Cultivos',
      'disease_button': 'Obtener asesoría de enfermedades',
      'disease_help': 'Ingrese cultivo y región arriba para obtener una asesoría de enfermedad en vivo.',
      'disease_crop': 'Cultivo',
      'disease_region': 'Región',
      'disease_symptoms': 'Síntomas observados',
      'disease_quality_score': 'Puntuación de calidad (1-10)',
      'disease_advisory': 'Asesoría',
      'disease_risk': 'Riesgo',
      'disease_confidence': 'Confianza',
      'disease_evidence': 'Evidencia',
      'farm_advisory_title': 'Sistema de Asesoría Agrícola',
      'farm_advisory_purpose': 'Ayude a los agricultores a administrar granjas, recopilar datos agrícolas en tiempo real y generar conjuntos de datos para volver a entrenar el modelo de predicción.',
      'farm_advisory_card_disease': 'Asesoría de Salud de Cultivos',
      'farm_advisory_card_disease_desc': 'Enfermedad, confianza y recomendaciones',
      'role_selection_continue_as': 'Continuar como',
      'farmer_registration_title': 'Registro de Agricultor',
      'farm_registration_title': 'Registro de Granja',
      'farm_registration_subtitle': 'Cada granja tiene sus propias coordenadas; un agricultor puede tener múltiples granjas en diferentes ubicaciones.',
      'farm_registration_name': 'Nombre de la granja',
      'farm_registration_size': 'Tamaño de la granja (acres)',
      'farm_registration_crop': 'Tipo de cultivo',
      'farm_registration_button': 'Registrar granja',
      'farm_activity_title': 'Seguimiento de Actividad de Granja',
      'farm_activity_save': 'Guardar actividad',
      'farm_activity_success': '¡Actividad registrada con éxito!',
      'farm_activity_dates': 'Por favor selecciona ambas fechas',
      'farm_activity_planting_date': 'Fecha de siembra',
      'farm_activity_crop_stage': 'Etapa del cultivo',
      'farm_activity_fertilizer_applied': 'Fertilizante Aplicado',
      'farm_activity_fertilizer_hint': 'p.ej. NPK 15-15-15',
      'farm_activity_enter_fertilizer': 'Ingrese el fertilizante aplicado',
      'farm_activity_expected_harvest_date': 'Fecha de cosecha esperada',
      'farm_advisory_buyer_search': 'Buscar productos en su lugar',
      'map_title': 'Mapa de Productos',
      'search_title': 'Buscar Productos',
      'search_filter_region': 'Filtrar por Región',
      'search_no_results': 'No se encontraron resultados para tu búsqueda.',
      'search_hint': 'Buscar cultivos, regiones, agricultores o cosechas',
      'weather_search_query': 'Buscar cultivos, regiones, agricultores o cosechas',
      'nav_search_label': 'Buscar productos',
      'no_produce_results': 'No se encontraron productos. Intenta otra búsqueda.',
      'by_location': 'Por ubicación',
      'individual_records': 'Registros individuales',
      'weather_refresh_location': 'Actualizar ubicación y clima',
      'weather_key_required': 'Por favor agrega tu clave de API de clima para continuar.',
      'language': 'Idioma',
      'language_english': 'Inglés',
      'language_spanish': 'Español',
      'location_gps_error': 'No se pudieron leer las coordenadas GPS.',
      'failed_disease_advisory': 'Error al cargar la asesoría de enfermedad: {error}',
      'enter_crop_region': 'Por favor ingresa cultivo y región.',
      'disease_unknown': 'Desconocido',
      'no_data_summary': 'Aún no hay datos. Ingresa cultivo y región para comenzar.',
      'farmer_registration_instructions': 'La ubicación potencia el asesoramiento climático, alertas de salud de cultivos y búsqueda de compradores por región.',
      'farmer_registration_full_name': 'Nombre completo',
      'farmer_registration_name_error': 'Ingresa tu nombre',
      'farmer_registration_phone': 'Número de teléfono',
      'farmer_registration_phone_error': 'Ingresa número de teléfono',
      'farmer_registration_location_title': 'Ubicación del agricultor',
      'farmer_registration_complete_form': 'Por favor completa el formulario',
      'farmer_registration_success_prefix': 'Agricultor registrado en',
      'map_coming_soon': 'Google Maps — próximamente',
      'map_active_producers': 'Productores activos',
      'prediction_region_x': 'Región: {region}',
      'prediction_card_predicted_quantity_desc': 'Basado en el tamaño de la granja y registros de actividades',
      'prediction_card_expected_harvest_desc': 'Ventana de cosecha óptima',
      'prediction_card_confidence_level_desc': 'Precisión del modelo para esta región',
      'prediction_confidence_breakdown': 'Desglose de confianza',
      'prediction_other_forecasts': 'Otros pronósticos de cultivos',
      'home_section_recent_predictions': 'Predicciones recientes',
      'prediction_expected_label': 'Esperado:',
      'search_by_location': 'Por ubicación',
      'search_individual_records': 'Registros individuales',
      'search_predicted_quantity': 'Cantidad predicha: {quantity}',
      'search_farmers': 'Agricultores: {count}',
      'search_farmer_label': 'Agricultor: {name}',
      'search_qty_label': 'Cantidad: {quantity}',
      'search_harvest_label': 'Cosecha: {harvest}',
      'availability_overview_title': 'Descripción general regional',
      'availability_quantity': 'Cantidad:',
      'availability_expected_harvest': 'Cosecha esperada:',
      'availability_confidence': 'Confianza:',
      'prediction_hub_title': 'Sistema de predicción de productos',
      'prediction_hub_purpose': 'Combina datos agrícolas históricos con datos de agricultores en tiempo real para predecir disponibilidad de cultivos, cantidad de cosecha y distribución regional de productos.',
      'prediction_hub_features_title': 'Características',
      'prediction_hub_model_inputs_title': 'Entradas del modelo',
      'prediction_hub_input_historical': 'Datos históricos',
      'prediction_hub_input_farmer': 'Datos de agricultores',
      'prediction_hub_input_weather': 'Datos meteorológicos',
      'prediction_hub_output_description': 'Salida: modelo entrenado que predice cantidad de cosecha, fechas de disponibilidad y distribución regional.',
      'regional_forecast_title': 'Pronóstico regional',
      'regional_forecast_description': 'Tendencias de producción por región (datos simulados)',
      'home_section_data': 'Datos generados',
    },
  };

  void setLocale(Locale locale) {
    if (!supportedLocales.contains(locale)) return;
    _locale = locale;
    notifyListeners();
  }

  String t(String key, {Map<String, String>? args}) {
    final values = _localizedValues[_locale.languageCode] ?? _localizedValues['en']!;
    var result = values[key] ?? key;
    if (args != null) {
      args.forEach((param, value) {
        result = result.replaceAll('{$param}', value);
      });
    }
    return result;
  }

  static AppLocalizations of(BuildContext context) {
    return context.watch<AppLocalizations>();
  }
}

extension LocalizationExtension on BuildContext {
  String t(String key, {Map<String, String>? args}) => AppLocalizations.of(this).t(key, args: args);
}
